#------------------------------------------------------------------------------
# Copyright 2019 Robert Cowart
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#------------------------------------------------------------------------------

version: '3'
networks:
  elastic:
services:
  elasticsearch-oss:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    container_name: elasticsearch-oss
    restart: 'no'
    hostname: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    ports:
      # REST
      - 9200:9200/tcp
      # Transport
      - 9300:9300/tcp
    volumes:
      - /var/lib/elasticsearch:/usr/share/elasticsearch/data
      - /var/log/elasticsearch:/usr/share/elasticsearch/logs
    environment:
      ES_JAVA_OPTS: '-Xms2g -Xmx2g'

      cluster.name: local
      
      node.master: 'true'
      node.data: 'true'
      node.ingest: 'true'

      #node.attr.avail_zone: az1
      #node.attr.data_temp: hot

      bootstrap.memory_lock: 'true'

      network.host: 0.0.0.0
      http.port: 9200

      action.destructive_requires_name: 'true'

      reindex.remote.whitelist: '[ "*.*.*.*:*" ]'

  kibana-oss:
    image: docker.elastic.co/kibana/kibana-oss:6.6.1
    container_name: kibana-oss
    depends_on:
      - elasticsearch-oss
    restart: 'no'
    hostname: kibana
    networks:
      - elastic
    ports:
      - 5601:5601/tcp
    environment:
      SERVER_NAME: localhost
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5601
      SERVER_MAXPAYLOADBYTES: 4194304

      ELASTICSEARCH_URL: http://elasticsearch:9200

      LOGGING_DEST: stdout
      #LOGGING_FALSE: 'false'
      LOGGING_QUIET: 'true'
      #LOGGING_VERBOSE: 'false'

      VEGA: '{"enableExternalUrls": true}'
