#------------------------------------------------------------------------------
# Copyright 2019 Robert Cowart
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#------------------------------------------------------------------------------

version: '3'
services:
  zoonavigator-web:
    image: elkozmon/zoonavigator-web:0.6.1
    container_name: zoonavigator-web
    restart: unless-stopped
    hostname: zoonavigator-web
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    environment:
      # Tells the HTTP server which port to bind to.
      # default: 8000
      WEB_HTTP_PORT: 8000

      # Specifies the host where ZooNavigator API runs.
      # default: api
      API_HOST: 192.0.2.11

      # Specifies the port where ZooNavigator API runs.
      # default: 9000
      API_PORT: 9000

      # Sets the timeout on requests to the ZooNavigator API. This value is in milliseconds.
      # default: 10000
      API_REQUEST_TIMEOUT_MILLIS: 10000

      # If set to true, tells web server to bind to all IPv6 addresses.
      # default: false
      #ENABLE_IPV6: "false"

      # If set, ZooNavigator will use this value as a default connection string and skip the connect form,
      # automatically connecting to listed ZooKeeper servers.
      #AUTO_CONNECT_CONNECTION_STRING: zk1:2181,zk2:2181,zk3:2181

      # In addition to presetting connection string as explained above, you can also set Auth info which ZooNavigator
      # will use to authenticate with ZooKeeper during the auto-connect. Use semicolon (;) to separate multiple
      # entries.
      #AUTO_CONNECT_AUTH_INFO: 
